name: terraform-checks

on:
  push: { paths: ["infra/terraform/**"] }
  pull_request: { paths: ["infra/terraform/**"] }

jobs:
  tf-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt (check)
        working-directory: infra/terraform
        run: terraform fmt -check -diff

      - name: Terraform init (no backend)
        working-directory: infra/terraform
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: infra/terraform
        run: terraform validate

      - name: TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: Run tflint
        working-directory: infra/terraform
        run: |
          tflint --init
          tflint
